export { default as Dashboard } from "./Dashboard"
export { default as Gallery } from "./Gallery"
export { default as Landing } from "./Landing"
export { default as Login } from "./Login"
export { default as Meet } from "./Meet"
export { default as Profile } from "./Profile"
export { default as Register } from "./Register"